version: '3.8'

services:
  init:
    image: alpine:latest
    volumes:
      - ./logs:/app/logs
      - ./user_prefs:/app/user_prefs
    entrypoint: >
      sh -c "
        mkdir -p /app/logs &&
        mkdir -p /app/user_prefs &&
        if [ ! -s /app/user_prefs/user_preferences.json ]; then
          echo '{}' > /app/user_prefs/user_preferences.json;
        fi
      "
    restart: "no"

  aibot:
    image: ghcr.io/goim01/aibot:main
    depends_on:
      - init
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./user_prefs:/app/user_prefs
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - XAI_API_KEY=${XAI_API_KEY}
      - MAX_TOKENS=3000
